# SPDX-FileCopyrightText: 2025 BlueHNT
# SPDX-FileCopyrightText: 2025 Whatstone
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipePack
  id: NFServiceStorage
  recipes:
  - NFBoxMREEmpty
  - NFHappyHonkEmpty
  - NFHappyHonkMimeEmpty
  - NFHappyHonkMcCargoEmpty
  - NFFoodBoxPizza
  - NFFoodBoxDonutEmpty
  - NFFoodBoxNuggetEmpty
  - NFFoodContainerEggEmpty
  - NFFoodBoxSushi
  - DrinkKegSteel
  - DrinkKegPlastic
  - DrinkKegWood

- type: latheRecipePack
  id: NFServiceStatic
  recipes:
  - Durathread # Frontier
  - FoodCondimentSqueezeBottleClear # Frontier
  - BucketPaper # Mono
  - PaperCup # Mono

- type: latheRecipePack
  id: NFService
  recipes:
  - ServiceSelectiveDropper # Frontier
  - PlantAnalyzer # Frontier
  - JanicartFlatpack # Frontier
  - PlantBagOfHolding # Delta-V

- type: latheRecipePack
  id: NFServiceBoardsStatic
  recipes:
  - CondimentDispenserCircuitboard

- type: latheRecipePack
  id: NFServiceBoards
  recipes:
  - KitchenAssemblerMachineCircuitboard # Frontier
  - ElectricRangeMachineCircuitboard # Frontier
  - ReagentGrinderMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - BiogeneratorMachineCircuitboard
  - DeepFryerMachineCircuitboard
