- type: job
  id: USSPRifleman
  name: job-name-ussp-rifleman
  description: job-description-ussp-rifleman
  playTimeTracker: JobUSSPRifleman
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 0
  startingGear: USSPRiflemanGear
  icon: "JobIconUSSPRifleman"
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  accessGroups:
  - GeneralAccess

- type: startingGear
  id: USSPRiflemanGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: MagazinePistol
  storage:
    back:
    - WeaponRifleAK502
