# SPDX-FileCopyrightText: 2025 BlueHNT
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipe
  id: PaperCup
  result: PaperCup
  categories:
  - Kitchen
  completetime: 2
  materials:
    Paper: 50